
homeassistant:
  customize:
    media_player.dianxinjidinghe:
      friendly_name: 电信机顶盒电视
      homebridge_name: 电信机顶盒电视
media_player:
  - platform: broadlink
    name: dianxinjidinghe
    host: 192.168.2.101
    mac: '34:EA:34:B5:3B:46' 
    ircodes_ini: broadlink_media_codes/dianxinjidinghe.ini
    ping_host: 192.168.2.13
group:
  media_players:
    view: yes
    icon: mdi:play-circle-outline
    entities:
      - group.media_player
  media_player:
    - media_player.dianxinjidinghe  
